version: '3.4'

services:

  mongo:
    image: mongo:${MONGO_VERSION}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - private
    ports:
      - 27018:27017
    volumes:
      - ./mongo/data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - private

  # client-portal-web:
  #   image: r88x66nm.c1.gra9.container-registry.ovh.net/klazzroom/client-portal-web
  #   volumes:
  #     - ./apps/client/portal/web/nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 4200:80


  api-gateway:
    image: r88x66nm.c1.gra9.container-registry.ovh.net/klazzroom/api-gateway
    environment:
      HOST: 0.0.0.0
    depends_on:
      - space-server
      - course-server
    networks:
      - private
    ports:
      - 3000:3000

  space-server:
    image: r88x66nm.c1.gra9.container-registry.ovh.net/klazzroom/server-space
    environment:
      HOST: 0.0.0.0
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/klazzroom_space
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - private

  course-server:
    image: r88x66nm.c1.gra9.container-registry.ovh.net/klazzroom/server-course
    environment:
      HOST: 0.0.0.0
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/klazzroom_course
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - private

  timetable-server:
    image: r88x66nm.c1.gra9.container-registry.ovh.net/klazzroom/server-timetable
    environment:
      HOST: 0.0.0.0
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/klazzroom_timetable
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - private

networks:
  private:
  public:
    name: traefik_webgateway
    external: true
