events {
    worker_connections 1024;
}
http {
    # Browser preferred language detection (does NOT require
    # AcceptLanguageModule)
    
    server {
        listen 80;
        server_name localhost;
        root /app;

        include /etc/nginx/mime.types;

        # Everything under the Angular application is always redirected to Angular in the
        # correct language
        location ~ ^/ {
            try_files $uri /index.html?$args;
        }
        # ...
    }
}

