query GetSpaces {
    me {
      spaces {
        ... on AdministratorSpace {
          id
          title
        }
        ... on TeacherSpace {
          id
          title
          courseId
        }
      }
    }
  }