query GetStudents($id: ID!) {
  course(id: $id) {
    id
    grades {
      id
      title
    }
    students {
      id
      firstname
      lastname
      grade {
        id
        title
      }
      birthday
      sex
      comments
      contacts {
        id
        firstname
        lastname
        emails {
          type
          value
        }
        phones {
          type
          value
        }
      }
    }
  }
}
